# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='电话号码'),
        ),
    ]
